name: Remote SSH Command
on:
  push:
    branches:
      - main
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Execute remote SSH commands using password
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.SSH_IP }}
          username: root
          password: ${{ secrets.SSH_PASSWORD }}
          port: 22
          script: |

            cd /root/topprix/Topprix
            git stash
            git pull origin main
            npm install --force
            tmux kill-session -t frontend || true
            tmux new-session -d -s frontend "npm run dev"

            cd /root/topprix/topprix_backend
            npm install --force
            tmux kill-session -t backend || true
            tmux new-session -d -s backend "npm run dev"

            cd /root/topprix/topprix_studio
            tmux kill-session -t studio || true
            tmux new-session -d -s studio "npx prisma studio"
